---
- name: Copy mysql_secure_installation.exp.j2.
  template:
    src: "mysql_secure_installation.exp.j2"
    dest: "/tmp/mysql_secure_installation.exp"
    mode: 0744

- name: Copy autogetpasswd.j2.
  template:
    src: "autogetpasswd.j2"
    dest: "/tmp/autogetpasswd.sh"
    mode: 0744

- name: Exec_autogetpasswd.sh.
  shell: "/usr/bin/bash  /tmp/autogetpasswd.sh"
  
- name: Exec_mysql_secure_installation.exp.
  shell: "/usr/bin/expect /tmp/mysql_secure_installation.exp"

- name: Ensure default user is present.
  mysql_user:
    name: "{{ mysql_user_name }}"
    host: "{{ mysql_user_host }}"
    password: "{{ mysql_user_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: mysql_user_name != mysql_root_username

- name: Copy user-my.cnf file with password credentials.
  template:
    src: "user-my.cnf.j2"
    dest: "{{ mysql_user_home }}/.my.cnf"
  when: mysql_user_name != mysql_root_username
   
- name: Copy .my.cnf file with root password credentials.
  template:
    src: "root-my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600
