---
- name: Install the MySQL repo.
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
    state: present
  when: ansible_os_family == "RedHat"  

- name: Override variables for MySQL (RedHat).
  set_fact:
    mysql_daemon: mysqld
    mysql_packages: ['mysql-community-server']
    mysql_log_error: /var/log/mysqld.err
    mysql_syslog_tag: mysqld
    mysql_pid_file: /var/run/mysqld/mysqld.pid
    mysql_socket: /var/lib/mysql/mysql.sock
  when: ansible_os_family == "RedHat"
  
- name: Installing dependencies
  package:
    name: "{{ mysql_dependencies }}"
    state: present
    
- name: Ensure MySQL packages are installed.
  yum:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: rh_mysql_install_packages

- name: Ensure MySQL is started and enabled on boot.
  service: "name={{ mysql_daemon }} state=started enabled={{ mysql_enabled_on_startup }}"
  register: mysql_service_configuration
